### ISSUE TITLE
Add ability to open BetterRep instead of button click in default UI

### ISSUE THREAD

**Issue by jrowles** [Kruithne/BetterRep#4]
Add the ability to open BetterRep immediately instead of going into the default reputation UI and clicking a button.

**Comment by Kruithne** [comment]
If you go into the game key-bindings, you can set up a key-binding to open BetterRep without needing to use the default reputation frame. Does that solve this for you?

**Comment by jrowles** [comment]
Yes, it does; however, you are only checking to close the BetterRep frame by game menu keybind.  It should also close on BetterRep keybind.  In my case, U is BetterRep keybind and Esc is game menu keybind.  Both Esc and U should close the BetterRep frame.

**Comment by Kruithne** [comment]
Yes, this is actually something I noted down the other day to fix. I will keep this issue as a reminder to fix that. Thanks.
